// Code generated by protoc-gen-go. DO NOT EDIT.
// source: web/proto/web.proto

package web

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

func init() { proto.RegisterFile("web/proto/web.proto", fileDescriptor_web_bef27c006c9b3eb3) }

var fileDescriptor_web_bef27c006c9b3eb3 = []byte{
	// 59 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2e, 0x4f, 0x4d, 0xd2,
	0x2f, 0x28, 0xca, 0x2f, 0xc9, 0xd7, 0x2f, 0x4f, 0x4d, 0xd2, 0x03, 0xb3, 0x84, 0x98, 0xcb, 0x53,
	0x93, 0x8c, 0x58, 0xb9, 0x98, 0xc3, 0x53, 0x93, 0x92, 0xd8, 0xc0, 0x42, 0xc6, 0x80, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x67, 0x68, 0x2a, 0x0c, 0x29, 0x00, 0x00, 0x00,
}
