version: "3.6"
services:
      
  web:
    image: instagram-bot/web
    build: ./web
    depends_on:
    - consul
    environment:
      MICRO_REGISTRY: "consul"
      MICRO_REGISTRY_ADDRESS: "consul"
    # HOSTNAME: "mydomain.com"
      WEB_PORT: 4040
      API_PORT: 4041
      DEBUG: 1
    ports:
    - 4040:4040
    entrypoint: ./instagram-bot.web

  api:
    image: instagram-bot/api
    build: ./api
    depends_on:
    - db
    - consul
    environment:
      MICRO_REGISTRY: "consul"
      MICRO_REGISTRY_ADDRESS: "consul"
    # HOSTNAME: "mydomain.com"
      WEB_PORT: 4040
      API_PORT: 4041
      DEBUG: 1
    ports:
    - 4041:4041
    entrypoint: ./instagram-bot.api

  htmlToimage:
    image: instagram-bot/htmltoimage
    build: ./htmlToimage
    depends_on:
    - consul
    environment:
      MICRO_REGISTRY: "consul"
      MICRO_REGISTRY_ADDRESS: "consul"
      DEBUG: 1
    entrypoint: ./htmlToimage

  sessions:
    image: instagram-bot/sessions
    build: ./sessions
    depends_on:
    - consul
    environment:
      MICRO_REGISTRY: "consul"
      MICRO_REGISTRY_ADDRESS: "consul"
      DEBUG: 1
    entrypoint: ./instagram-bot.sessions

  facedetect:
    image: instagram-bot/facedetect
    build: ./faceDetect
    depends_on:
    - consul

  consul:
    image: consul:latest
    command: agent -server -bootstrap-expect=1 -log-level=warn -ui -client=0.0.0.0
    hostname: consul
    ports:
    - 8500:8500

  db:
    image: postgres:10.4
    container_name: web-db
    environment:
      DB_NAME: insta_db
      DB_USER: test
      DB_PASS: test
    ports:
    - 5432:5432
    expose:
    - 5432
