version: "3.6"
services:
      
  web:
    image: instagram-bot/web
    build: ./web
    depends_on:
    - db
    - consul
    environment:
      MICRO_REGISTRY: "consul"
      MICRO_REGISTRY_ADDRESS: "consul"
      DEBUG: 1
    ports:
    - 4040:4040
    entrypoint: ./instagram-bot.web http://localhost:4040

  htmlToimage:
    image: instagram-bot/htmltoimage
    build: ./htmlToimage
    depends_on:
    - consul
    environment:
      MICRO_REGISTRY: "consul"
      MICRO_REGISTRY_ADDRESS: "consul"
      DEBUG: 1
    entrypoint: ./htmltoimage

  sessions:
    image: instagram-bot/sessions
    build: ./sessions
    depends_on:
    - consul
    environment:
      MICRO_REGISTRY: "consul"
      MICRO_REGISTRY_ADDRESS: "consul"
      DEBUG: 1
    entrypoint: ./instagram-bot.sessions

  consul:
    image: consul:latest
    command: agent -server -bootstrap-expect=1 -log-level=warn -ui -client=0.0.0.0
    hostname: consul
    ports:
    - 8500:8500

  db:
    image: mysql:5.7
    container_name: web-db
    environment:
      MYSQL_DATABASE: insta_db
      MYSQL_ROOT_PASSWORD: root
    ports:
    - 3306:3306
    expose:
    - 3306
