apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: default
  name: apidepl
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        command: [
      		"./instagram-bot.api",
      		"--server_address=0.0.0.0:8080",
      		"--broker_address=0.0.0.0:10001",
      		"--selector=static",
      	]
        image: livelance/api:v0.0.1
        env:
          - name: WEB_HOST
            value: "http://192.168.99.100:30001"
          - name: DB_USER
            value: "postgres"
        #  - name: DB_PASS
         #t   value: "test"
          - name: DB_NAME
            value: "insta_db"
        ports:
        - containerPort: 8080
          name: srvc-port
        - containerPort: 8081
          name: api-port
