// Code generated by protoc-gen-go. DO NOT EDIT.
// source: session.proto

package sessions_proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SessionRequest struct {
	Account              string   `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SessionRequest) Reset()         { *m = SessionRequest{} }
func (m *SessionRequest) String() string { return proto.CompactTextString(m) }
func (*SessionRequest) ProtoMessage()    {}
func (*SessionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_session_0b3c2ea315973391, []int{0}
}
func (m *SessionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionRequest.Unmarshal(m, b)
}
func (m *SessionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionRequest.Marshal(b, m, deterministic)
}
func (dst *SessionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionRequest.Merge(dst, src)
}
func (m *SessionRequest) XXX_Size() int {
	return xxx_messageInfo_SessionRequest.Size(m)
}
func (m *SessionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SessionRequest proto.InternalMessageInfo

func (m *SessionRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *SessionRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type SessionResponse struct {
	Error                string   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SessionResponse) Reset()         { *m = SessionResponse{} }
func (m *SessionResponse) String() string { return proto.CompactTextString(m) }
func (*SessionResponse) ProtoMessage()    {}
func (*SessionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_session_0b3c2ea315973391, []int{1}
}
func (m *SessionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionResponse.Unmarshal(m, b)
}
func (m *SessionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionResponse.Marshal(b, m, deterministic)
}
func (dst *SessionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionResponse.Merge(dst, src)
}
func (m *SessionResponse) XXX_Size() int {
	return xxx_messageInfo_SessionResponse.Size(m)
}
func (m *SessionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SessionResponse proto.InternalMessageInfo

func (m *SessionResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type Users struct {
	Users                []*User  `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Users) Reset()         { *m = Users{} }
func (m *Users) String() string { return proto.CompactTextString(m) }
func (*Users) ProtoMessage()    {}
func (*Users) Descriptor() ([]byte, []int) {
	return fileDescriptor_session_0b3c2ea315973391, []int{2}
}
func (m *Users) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Users.Unmarshal(m, b)
}
func (m *Users) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Users.Marshal(b, m, deterministic)
}
func (dst *Users) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Users.Merge(dst, src)
}
func (m *Users) XXX_Size() int {
	return xxx_messageInfo_Users.Size(m)
}
func (m *Users) XXX_DiscardUnknown() {
	xxx_messageInfo_Users.DiscardUnknown(m)
}

var xxx_messageInfo_Users proto.InternalMessageInfo

func (m *Users) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

type UserReq struct {
	Account              string   `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=Username,proto3" json:"Username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserReq) Reset()         { *m = UserReq{} }
func (m *UserReq) String() string { return proto.CompactTextString(m) }
func (*UserReq) ProtoMessage()    {}
func (*UserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_session_0b3c2ea315973391, []int{3}
}
func (m *UserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserReq.Unmarshal(m, b)
}
func (m *UserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserReq.Marshal(b, m, deterministic)
}
func (dst *UserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserReq.Merge(dst, src)
}
func (m *UserReq) XXX_Size() int {
	return xxx_messageInfo_UserReq.Size(m)
}
func (m *UserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UserReq.DiscardUnknown(m)
}

var xxx_messageInfo_UserReq proto.InternalMessageInfo

func (m *UserReq) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *UserReq) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type UserResp struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserResp) Reset()         { *m = UserResp{} }
func (m *UserResp) String() string { return proto.CompactTextString(m) }
func (*UserResp) ProtoMessage()    {}
func (*UserResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_session_0b3c2ea315973391, []int{4}
}
func (m *UserResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserResp.Unmarshal(m, b)
}
func (m *UserResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserResp.Marshal(b, m, deterministic)
}
func (dst *UserResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserResp.Merge(dst, src)
}
func (m *UserResp) XXX_Size() int {
	return xxx_messageInfo_UserResp.Size(m)
}
func (m *UserResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UserResp.DiscardUnknown(m)
}

var xxx_messageInfo_UserResp proto.InternalMessageInfo

func (m *UserResp) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type User struct {
	Username             string   `protobuf:"bytes,1,opt,name=Username,proto3" json:"Username,omitempty"`
	FullName             string   `protobuf:"bytes,2,opt,name=FullName,proto3" json:"FullName,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=Description,proto3" json:"Description,omitempty"`
	FollowerCount        int64    `protobuf:"varint,4,opt,name=FollowerCount,proto3" json:"FollowerCount,omitempty"`
	ProfilePicUrl        string   `protobuf:"bytes,5,opt,name=ProfilePicUrl,proto3" json:"ProfilePicUrl,omitempty"`
	FeaturedPicUrl       string   `protobuf:"bytes,6,opt,name=FeaturedPicUrl,proto3" json:"FeaturedPicUrl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_session_0b3c2ea315973391, []int{5}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

func (m *User) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *User) GetFollowerCount() int64 {
	if m != nil {
		return m.FollowerCount
	}
	return 0
}

func (m *User) GetProfilePicUrl() string {
	if m != nil {
		return m.ProfilePicUrl
	}
	return ""
}

func (m *User) GetFeaturedPicUrl() string {
	if m != nil {
		return m.FeaturedPicUrl
	}
	return ""
}

type MessageRequest struct {
	Sender               string   `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Recipient            string   `protobuf:"bytes,2,opt,name=recipient,proto3" json:"recipient,omitempty"`
	Text                 string   `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	Title                string   `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageRequest) Reset()         { *m = MessageRequest{} }
func (m *MessageRequest) String() string { return proto.CompactTextString(m) }
func (*MessageRequest) ProtoMessage()    {}
func (*MessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_session_0b3c2ea315973391, []int{6}
}
func (m *MessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageRequest.Unmarshal(m, b)
}
func (m *MessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageRequest.Marshal(b, m, deterministic)
}
func (dst *MessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageRequest.Merge(dst, src)
}
func (m *MessageRequest) XXX_Size() int {
	return xxx_messageInfo_MessageRequest.Size(m)
}
func (m *MessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MessageRequest proto.InternalMessageInfo

func (m *MessageRequest) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *MessageRequest) GetRecipient() string {
	if m != nil {
		return m.Recipient
	}
	return ""
}

func (m *MessageRequest) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *MessageRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

type MessageResponse struct {
	Response             string   `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageResponse) Reset()         { *m = MessageResponse{} }
func (m *MessageResponse) String() string { return proto.CompactTextString(m) }
func (*MessageResponse) ProtoMessage()    {}
func (*MessageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_session_0b3c2ea315973391, []int{7}
}
func (m *MessageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageResponse.Unmarshal(m, b)
}
func (m *MessageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageResponse.Marshal(b, m, deterministic)
}
func (dst *MessageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageResponse.Merge(dst, src)
}
func (m *MessageResponse) XXX_Size() int {
	return xxx_messageInfo_MessageResponse.Size(m)
}
func (m *MessageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MessageResponse proto.InternalMessageInfo

func (m *MessageResponse) GetResponse() string {
	if m != nil {
		return m.Response
	}
	return ""
}

func (m *MessageResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*SessionRequest)(nil), "sessions.proto.SessionRequest")
	proto.RegisterType((*SessionResponse)(nil), "sessions.proto.SessionResponse")
	proto.RegisterType((*Users)(nil), "sessions.proto.Users")
	proto.RegisterType((*UserReq)(nil), "sessions.proto.UserReq")
	proto.RegisterType((*UserResp)(nil), "sessions.proto.UserResp")
	proto.RegisterType((*User)(nil), "sessions.proto.User")
	proto.RegisterType((*MessageRequest)(nil), "sessions.proto.MessageRequest")
	proto.RegisterType((*MessageResponse)(nil), "sessions.proto.MessageResponse")
}

func init() { proto.RegisterFile("session.proto", fileDescriptor_session_0b3c2ea315973391) }

var fileDescriptor_session_0b3c2ea315973391 = []byte{
	// 456 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x53, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x8d, 0xf3, 0xd9, 0x4c, 0xd5, 0x54, 0x1a, 0x15, 0xb0, 0x22, 0x04, 0xd1, 0x0a, 0x41, 0xc4,
	0x21, 0x87, 0x96, 0x7b, 0x0f, 0x45, 0xa1, 0x88, 0x0f, 0x55, 0x46, 0xfd, 0x01, 0xc6, 0x99, 0x22,
	0x4b, 0xee, 0xae, 0xb3, 0xb3, 0xa6, 0xfc, 0x50, 0xfe, 0x0c, 0x37, 0xb4, 0x1f, 0x36, 0x71, 0x3e,
	0xe0, 0xc2, 0x6d, 0xdf, 0x9b, 0xe7, 0xb7, 0x33, 0x3b, 0xcf, 0x70, 0xc2, 0xc4, 0x9c, 0x2b, 0xb9,
	0x28, 0xb5, 0x32, 0x0a, 0x27, 0x01, 0xb2, 0xc7, 0x62, 0x09, 0x93, 0x2f, 0x9e, 0x49, 0x68, 0x5d,
	0x11, 0x1b, 0x8c, 0x61, 0x94, 0x66, 0x99, 0xaa, 0xa4, 0x89, 0xa3, 0x59, 0x34, 0x1f, 0x27, 0x35,
	0xc4, 0x29, 0x1c, 0x95, 0x29, 0xf3, 0x83, 0xd2, 0xab, 0xb8, 0xeb, 0x4a, 0x0d, 0x16, 0xaf, 0xe0,
	0xb4, 0xf1, 0xe1, 0x52, 0x49, 0x26, 0x3c, 0x83, 0x01, 0x69, 0xad, 0x74, 0xb0, 0xf1, 0x40, 0x5c,
	0xc0, 0xe0, 0x96, 0x49, 0x33, 0xbe, 0x86, 0x41, 0x65, 0x0f, 0x71, 0x34, 0xeb, 0xcd, 0x8f, 0xcf,
	0xcf, 0x16, 0xed, 0xce, 0x16, 0x56, 0x95, 0x78, 0x89, 0xb8, 0x84, 0x91, 0x83, 0xb4, 0xfe, 0x7b,
	0x7b, 0x56, 0x24, 0xd3, 0x7b, 0xaa, 0xdb, 0xab, 0xb1, 0x78, 0xe3, 0x6b, 0xb6, 0x37, 0x9c, 0x43,
	0xdf, 0xba, 0xba, 0xcf, 0x0f, 0xdd, 0xeb, 0x14, 0xe2, 0x67, 0x04, 0x7d, 0x0b, 0x5b, 0xd6, 0x51,
	0xdb, 0xda, 0xd6, 0x96, 0x55, 0x51, 0x7c, 0xde, 0xb8, 0xb6, 0xc6, 0x38, 0x83, 0xe3, 0xb7, 0xc4,
	0x99, 0xce, 0x4b, 0x93, 0x2b, 0x19, 0xf7, 0x5c, 0x79, 0x93, 0xc2, 0x17, 0x70, 0xb2, 0x54, 0x45,
	0xa1, 0x1e, 0x48, 0x5f, 0xb9, 0xa1, 0xfa, 0xb3, 0x68, 0xde, 0x4b, 0xda, 0xa4, 0x55, 0xdd, 0x68,
	0x75, 0x97, 0x17, 0x74, 0x93, 0x67, 0xb7, 0xba, 0x88, 0x07, 0xce, 0xa9, 0x4d, 0xe2, 0x4b, 0x98,
	0x2c, 0x29, 0x35, 0x95, 0xa6, 0x55, 0x90, 0x0d, 0x9d, 0x6c, 0x8b, 0x15, 0x25, 0x4c, 0x3e, 0x11,
	0x73, 0xfa, 0x8d, 0xea, 0x9d, 0x3f, 0x86, 0x21, 0x93, 0x5c, 0x51, 0xbd, 0xab, 0x80, 0xf0, 0x29,
	0x8c, 0x35, 0x65, 0x79, 0x99, 0x93, 0x34, 0x61, 0xb8, 0x3f, 0x04, 0x22, 0xf4, 0x0d, 0xfd, 0x30,
	0x61, 0x2c, 0x77, 0xb6, 0x4b, 0x37, 0xb9, 0x29, 0xc8, 0xcd, 0x31, 0x4e, 0x3c, 0x10, 0x57, 0x70,
	0xda, 0xdc, 0x18, 0xd2, 0x31, 0x85, 0x23, 0x1d, 0xce, 0xf5, 0x93, 0xea, 0x9d, 0xe4, 0x74, 0x37,
	0x92, 0x73, 0xfe, 0xab, 0x0b, 0xa3, 0x90, 0x31, 0xbc, 0x86, 0xde, 0x3b, 0x32, 0xf8, 0x6c, 0x7b,
	0x79, 0xed, 0x2c, 0x4f, 0x9f, 0x1f, 0xac, 0xfb, 0x9b, 0x44, 0x07, 0x3f, 0xc0, 0x30, 0xa1, 0x7b,
	0xf5, 0x9d, 0xfe, 0x87, 0xd9, 0x47, 0x18, 0x85, 0x39, 0x77, 0xdd, 0xda, 0x4f, 0xbe, 0xeb, 0xb6,
	0xf5, 0x40, 0xa2, 0x83, 0xd7, 0x4d, 0x36, 0x56, 0xfe, 0x97, 0xf9, 0x57, 0x87, 0x8f, 0xf6, 0x65,
	0x99, 0x45, 0x07, 0x2f, 0x7d, 0x7e, 0xdf, 0xcb, 0x3b, 0x85, 0x4f, 0xf6, 0x06, 0x9e, 0xd6, 0xd3,
	0x78, 0x7f, 0x81, 0x4b, 0xd1, 0xf9, 0x3a, 0x74, 0xcc, 0xc5, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff,
	0xa0, 0xcd, 0x27, 0xc8, 0x4e, 0x04, 0x00, 0x00,
}
