// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: web/proto/web.proto

/*
Package web is a generated protocol buffer package.

It is generated from these files:
	web/proto/web.proto

It has these top-level messages:
*/
package web

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Web service

type WebService interface {
}

type webService struct {
	c    client.Client
	name string
}

func NewWebService(name string, c client.Client) WebService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "web"
	}
	return &webService{
		c:    c,
		name: name,
	}
}

// Server API for Web service

type WebHandler interface {
}

func RegisterWebHandler(s server.Server, hdlr WebHandler, opts ...server.HandlerOption) {
	type web interface {
	}
	type Web struct {
		web
	}
	h := &webHandler{hdlr}
	s.Handle(s.NewHandler(&Web{h}, opts...))
}

type webHandler struct {
	WebHandler
}
