// Code generated by protoc-gen-go. DO NOT EDIT.
// source: web.proto

package instagram_bot_web

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type JobReq struct {
	Hashtag              string   `protobuf:"bytes,1,opt,name=hashtag,proto3" json:"hashtag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JobReq) Reset()         { *m = JobReq{} }
func (m *JobReq) String() string { return proto.CompactTextString(m) }
func (*JobReq) ProtoMessage()    {}
func (*JobReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_web_174c6c71d001ead1, []int{0}
}
func (m *JobReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobReq.Unmarshal(m, b)
}
func (m *JobReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobReq.Marshal(b, m, deterministic)
}
func (dst *JobReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobReq.Merge(dst, src)
}
func (m *JobReq) XXX_Size() int {
	return xxx_messageInfo_JobReq.Size(m)
}
func (m *JobReq) XXX_DiscardUnknown() {
	xxx_messageInfo_JobReq.DiscardUnknown(m)
}

var xxx_messageInfo_JobReq proto.InternalMessageInfo

func (m *JobReq) GetHashtag() string {
	if m != nil {
		return m.Hashtag
	}
	return ""
}

type JobResp struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Hashtag              string   `protobuf:"bytes,2,opt,name=hashtag,proto3" json:"hashtag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JobResp) Reset()         { *m = JobResp{} }
func (m *JobResp) String() string { return proto.CompactTextString(m) }
func (*JobResp) ProtoMessage()    {}
func (*JobResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_web_174c6c71d001ead1, []int{1}
}
func (m *JobResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobResp.Unmarshal(m, b)
}
func (m *JobResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobResp.Marshal(b, m, deterministic)
}
func (dst *JobResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobResp.Merge(dst, src)
}
func (m *JobResp) XXX_Size() int {
	return xxx_messageInfo_JobResp.Size(m)
}
func (m *JobResp) XXX_DiscardUnknown() {
	xxx_messageInfo_JobResp.DiscardUnknown(m)
}

var xxx_messageInfo_JobResp proto.InternalMessageInfo

func (m *JobResp) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *JobResp) GetHashtag() string {
	if m != nil {
		return m.Hashtag
	}
	return ""
}

type Users struct {
	Users                []*User  `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Users) Reset()         { *m = Users{} }
func (m *Users) String() string { return proto.CompactTextString(m) }
func (*Users) ProtoMessage()    {}
func (*Users) Descriptor() ([]byte, []int) {
	return fileDescriptor_web_174c6c71d001ead1, []int{2}
}
func (m *Users) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Users.Unmarshal(m, b)
}
func (m *Users) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Users.Marshal(b, m, deterministic)
}
func (dst *Users) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Users.Merge(dst, src)
}
func (m *Users) XXX_Size() int {
	return xxx_messageInfo_Users.Size(m)
}
func (m *Users) XXX_DiscardUnknown() {
	xxx_messageInfo_Users.DiscardUnknown(m)
}

var xxx_messageInfo_Users proto.InternalMessageInfo

func (m *Users) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

type UserReq struct {
	Username             string   `protobuf:"bytes,1,opt,name=Username,proto3" json:"Username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserReq) Reset()         { *m = UserReq{} }
func (m *UserReq) String() string { return proto.CompactTextString(m) }
func (*UserReq) ProtoMessage()    {}
func (*UserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_web_174c6c71d001ead1, []int{3}
}
func (m *UserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserReq.Unmarshal(m, b)
}
func (m *UserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserReq.Marshal(b, m, deterministic)
}
func (dst *UserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserReq.Merge(dst, src)
}
func (m *UserReq) XXX_Size() int {
	return xxx_messageInfo_UserReq.Size(m)
}
func (m *UserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UserReq.DiscardUnknown(m)
}

var xxx_messageInfo_UserReq proto.InternalMessageInfo

func (m *UserReq) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type UserResp struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserResp) Reset()         { *m = UserResp{} }
func (m *UserResp) String() string { return proto.CompactTextString(m) }
func (*UserResp) ProtoMessage()    {}
func (*UserResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_web_174c6c71d001ead1, []int{4}
}
func (m *UserResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserResp.Unmarshal(m, b)
}
func (m *UserResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserResp.Marshal(b, m, deterministic)
}
func (dst *UserResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserResp.Merge(dst, src)
}
func (m *UserResp) XXX_Size() int {
	return xxx_messageInfo_UserResp.Size(m)
}
func (m *UserResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UserResp.DiscardUnknown(m)
}

var xxx_messageInfo_UserResp proto.InternalMessageInfo

func (m *UserResp) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type User struct {
	Username             string   `protobuf:"bytes,1,opt,name=Username,proto3" json:"Username,omitempty"`
	FullName             string   `protobuf:"bytes,2,opt,name=FullName,proto3" json:"FullName,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=Description,proto3" json:"Description,omitempty"`
	FollowerCount        int64    `protobuf:"varint,4,opt,name=FollowerCount,proto3" json:"FollowerCount,omitempty"`
	ProfilePicUrl        string   `protobuf:"bytes,5,opt,name=ProfilePicUrl,proto3" json:"ProfilePicUrl,omitempty"`
	FeaturedPicUrl       string   `protobuf:"bytes,6,opt,name=FeaturedPicUrl,proto3" json:"FeaturedPicUrl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_web_174c6c71d001ead1, []int{5}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

func (m *User) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *User) GetFollowerCount() int64 {
	if m != nil {
		return m.FollowerCount
	}
	return 0
}

func (m *User) GetProfilePicUrl() string {
	if m != nil {
		return m.ProfilePicUrl
	}
	return ""
}

func (m *User) GetFeaturedPicUrl() string {
	if m != nil {
		return m.FeaturedPicUrl
	}
	return ""
}

func init() {
	proto.RegisterType((*JobReq)(nil), "instagram.bot.web.JobReq")
	proto.RegisterType((*JobResp)(nil), "instagram.bot.web.JobResp")
	proto.RegisterType((*Users)(nil), "instagram.bot.web.Users")
	proto.RegisterType((*UserReq)(nil), "instagram.bot.web.UserReq")
	proto.RegisterType((*UserResp)(nil), "instagram.bot.web.UserResp")
	proto.RegisterType((*User)(nil), "instagram.bot.web.User")
}

func init() { proto.RegisterFile("web.proto", fileDescriptor_web_174c6c71d001ead1) }

var fileDescriptor_web_174c6c71d001ead1 = []byte{
	// 327 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0x4f, 0x4f, 0xf2, 0x40,
	0x10, 0xc6, 0xdf, 0x52, 0xfe, 0xbc, 0x0c, 0x91, 0xc4, 0xbd, 0x58, 0xeb, 0x85, 0x6c, 0xd4, 0x90,
	0x18, 0x7b, 0x80, 0x44, 0x6f, 0x26, 0x46, 0xc3, 0x81, 0x83, 0x21, 0x4d, 0x88, 0xe7, 0x5d, 0x18,
	0x61, 0x93, 0xa5, 0x5b, 0x76, 0xb7, 0xe1, 0x2b, 0xf8, 0x01, 0xfd, 0x40, 0x66, 0xb7, 0x40, 0x40,
	0x2d, 0xb7, 0x79, 0xe6, 0xf9, 0xcd, 0x74, 0xfa, 0xb4, 0xd0, 0xde, 0x20, 0x4f, 0x72, 0xad, 0xac,
	0x22, 0xe7, 0x22, 0x33, 0x96, 0x2d, 0x34, 0x5b, 0x25, 0x5c, 0xd9, 0x64, 0x83, 0x9c, 0x52, 0x68,
	0x8e, 0x15, 0x4f, 0x71, 0x4d, 0x22, 0x68, 0x2d, 0x99, 0x59, 0x5a, 0xb6, 0x88, 0x82, 0x5e, 0xd0,
	0x6f, 0xa7, 0x3b, 0x49, 0x87, 0xd0, 0xf2, 0x8c, 0xc9, 0x49, 0x17, 0x6a, 0x62, 0xee, 0xfd, 0x30,
	0xad, 0x89, 0xf9, 0xe1, 0x50, 0xed, 0x78, 0xe8, 0x01, 0x1a, 0x53, 0x83, 0xda, 0x90, 0x7b, 0x68,
	0x14, 0xae, 0x88, 0x82, 0x5e, 0xd8, 0xef, 0x0c, 0x2e, 0x92, 0x5f, 0x47, 0x24, 0x0e, 0x4c, 0x4b,
	0x8a, 0xde, 0x40, 0xcb, 0x4b, 0x5c, 0x93, 0x18, 0xfe, 0xbb, 0x32, 0x63, 0x2b, 0xdc, 0x9e, 0xb4,
	0xd7, 0xf4, 0xb1, 0xf4, 0xfc, 0x51, 0x77, 0x50, 0x77, 0xb3, 0x9e, 0x39, 0xf1, 0x00, 0x0f, 0xd1,
	0xaf, 0x00, 0xea, 0x4e, 0x9e, 0xda, 0xee, 0xbc, 0x51, 0x21, 0xe5, 0x9b, 0xf3, 0xca, 0xf7, 0xda,
	0x6b, 0xd2, 0x83, 0xce, 0x2b, 0x9a, 0x99, 0x16, 0xb9, 0x15, 0x2a, 0x8b, 0x42, 0x6f, 0x1f, 0xb6,
	0xc8, 0x35, 0x9c, 0x8d, 0x94, 0x94, 0x6a, 0x83, 0xfa, 0x45, 0x15, 0x99, 0x8d, 0xea, 0x3e, 0xaf,
	0xe3, 0xa6, 0xa3, 0x26, 0x5a, 0x7d, 0x08, 0x89, 0x13, 0x31, 0x9b, 0x6a, 0x19, 0x35, 0xfc, 0xa6,
	0xe3, 0x26, 0xb9, 0x85, 0xee, 0x08, 0x99, 0x2d, 0x34, 0xce, 0xb7, 0x58, 0xd3, 0x63, 0x3f, 0xba,
	0x83, 0xcf, 0x00, 0xc2, 0x77, 0xe4, 0xe4, 0x09, 0xc2, 0xb1, 0xe2, 0xe4, 0xf2, 0x8f, 0x10, 0xca,
	0xef, 0x1c, 0xc7, 0x55, 0x96, 0xc9, 0xe9, 0x3f, 0xf2, 0xbc, 0x4b, 0xa7, 0x2a, 0x45, 0x5c, 0xc7,
	0x57, 0x95, 0x9e, 0x5b, 0xc1, 0x9b, 0xfe, 0x67, 0x1b, 0x7e, 0x07, 0x00, 0x00, 0xff, 0xff, 0x91,
	0xe2, 0xea, 0xb1, 0x79, 0x02, 0x00, 0x00,
}
