// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: web.proto

/*
Package instagram_bot_web is a generated protocol buffer package.

It is generated from these files:
	web.proto

It has these top-level messages:
	JobReq
	JobResp
	Users
	UserReq
	UserResp
	User
*/
package instagram_bot_web

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Web service

type WebService interface {
	Job(ctx context.Context, in *JobReq, opts ...client.CallOption) (*JobResp, error)
	User(ctx context.Context, in *UserReq, opts ...client.CallOption) (*UserResp, error)
}

type webService struct {
	c    client.Client
	name string
}

func NewWebService(name string, c client.Client) WebService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "instagram.bot.web"
	}
	return &webService{
		c:    c,
		name: name,
	}
}

func (c *webService) Job(ctx context.Context, in *JobReq, opts ...client.CallOption) (*JobResp, error) {
	req := c.c.NewRequest(c.name, "Web.Job", in)
	out := new(JobResp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webService) User(ctx context.Context, in *UserReq, opts ...client.CallOption) (*UserResp, error) {
	req := c.c.NewRequest(c.name, "Web.User", in)
	out := new(UserResp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Web service

type WebHandler interface {
	Job(context.Context, *JobReq, *JobResp) error
	User(context.Context, *UserReq, *UserResp) error
}

func RegisterWebHandler(s server.Server, hdlr WebHandler, opts ...server.HandlerOption) {
	type web interface {
		Job(ctx context.Context, in *JobReq, out *JobResp) error
		User(ctx context.Context, in *UserReq, out *UserResp) error
	}
	type Web struct {
		web
	}
	h := &webHandler{hdlr}
	s.Handle(s.NewHandler(&Web{h}, opts...))
}

type webHandler struct {
	WebHandler
}

func (h *webHandler) Job(ctx context.Context, in *JobReq, out *JobResp) error {
	return h.WebHandler.Job(ctx, in, out)
}

func (h *webHandler) User(ctx context.Context, in *UserReq, out *UserResp) error {
	return h.WebHandler.User(ctx, in, out)
}
