// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type LoginReq struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginReq) Reset()         { *m = LoginReq{} }
func (m *LoginReq) String() string { return proto.CompactTextString(m) }
func (*LoginReq) ProtoMessage()    {}
func (*LoginReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_814acf6c55e120a3, []int{0}
}
func (m *LoginReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginReq.Unmarshal(m, b)
}
func (m *LoginReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginReq.Marshal(b, m, deterministic)
}
func (dst *LoginReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginReq.Merge(dst, src)
}
func (m *LoginReq) XXX_Size() int {
	return xxx_messageInfo_LoginReq.Size(m)
}
func (m *LoginReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginReq.DiscardUnknown(m)
}

var xxx_messageInfo_LoginReq proto.InternalMessageInfo

func (m *LoginReq) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type LoginResp struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResp) Reset()         { *m = LoginResp{} }
func (m *LoginResp) String() string { return proto.CompactTextString(m) }
func (*LoginResp) ProtoMessage()    {}
func (*LoginResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_814acf6c55e120a3, []int{1}
}
func (m *LoginResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResp.Unmarshal(m, b)
}
func (m *LoginResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResp.Marshal(b, m, deterministic)
}
func (dst *LoginResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResp.Merge(dst, src)
}
func (m *LoginResp) XXX_Size() int {
	return xxx_messageInfo_LoginResp.Size(m)
}
func (m *LoginResp) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResp.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResp proto.InternalMessageInfo

func (m *LoginResp) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type JobReq struct {
	Hashtag              string   `protobuf:"bytes,1,opt,name=hashtag,proto3" json:"hashtag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JobReq) Reset()         { *m = JobReq{} }
func (m *JobReq) String() string { return proto.CompactTextString(m) }
func (*JobReq) ProtoMessage()    {}
func (*JobReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_814acf6c55e120a3, []int{2}
}
func (m *JobReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobReq.Unmarshal(m, b)
}
func (m *JobReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobReq.Marshal(b, m, deterministic)
}
func (dst *JobReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobReq.Merge(dst, src)
}
func (m *JobReq) XXX_Size() int {
	return xxx_messageInfo_JobReq.Size(m)
}
func (m *JobReq) XXX_DiscardUnknown() {
	xxx_messageInfo_JobReq.DiscardUnknown(m)
}

var xxx_messageInfo_JobReq proto.InternalMessageInfo

func (m *JobReq) GetHashtag() string {
	if m != nil {
		return m.Hashtag
	}
	return ""
}

type JobResp struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Hashtag              string   `protobuf:"bytes,2,opt,name=hashtag,proto3" json:"hashtag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JobResp) Reset()         { *m = JobResp{} }
func (m *JobResp) String() string { return proto.CompactTextString(m) }
func (*JobResp) ProtoMessage()    {}
func (*JobResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_814acf6c55e120a3, []int{3}
}
func (m *JobResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobResp.Unmarshal(m, b)
}
func (m *JobResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobResp.Marshal(b, m, deterministic)
}
func (dst *JobResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobResp.Merge(dst, src)
}
func (m *JobResp) XXX_Size() int {
	return xxx_messageInfo_JobResp.Size(m)
}
func (m *JobResp) XXX_DiscardUnknown() {
	xxx_messageInfo_JobResp.DiscardUnknown(m)
}

var xxx_messageInfo_JobResp proto.InternalMessageInfo

func (m *JobResp) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *JobResp) GetHashtag() string {
	if m != nil {
		return m.Hashtag
	}
	return ""
}

type Users struct {
	Users                []*User  `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Users) Reset()         { *m = Users{} }
func (m *Users) String() string { return proto.CompactTextString(m) }
func (*Users) ProtoMessage()    {}
func (*Users) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_814acf6c55e120a3, []int{4}
}
func (m *Users) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Users.Unmarshal(m, b)
}
func (m *Users) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Users.Marshal(b, m, deterministic)
}
func (dst *Users) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Users.Merge(dst, src)
}
func (m *Users) XXX_Size() int {
	return xxx_messageInfo_Users.Size(m)
}
func (m *Users) XXX_DiscardUnknown() {
	xxx_messageInfo_Users.DiscardUnknown(m)
}

var xxx_messageInfo_Users proto.InternalMessageInfo

func (m *Users) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

type UserReq struct {
	Username             string   `protobuf:"bytes,1,opt,name=Username,proto3" json:"Username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserReq) Reset()         { *m = UserReq{} }
func (m *UserReq) String() string { return proto.CompactTextString(m) }
func (*UserReq) ProtoMessage()    {}
func (*UserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_814acf6c55e120a3, []int{5}
}
func (m *UserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserReq.Unmarshal(m, b)
}
func (m *UserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserReq.Marshal(b, m, deterministic)
}
func (dst *UserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserReq.Merge(dst, src)
}
func (m *UserReq) XXX_Size() int {
	return xxx_messageInfo_UserReq.Size(m)
}
func (m *UserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UserReq.DiscardUnknown(m)
}

var xxx_messageInfo_UserReq proto.InternalMessageInfo

func (m *UserReq) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type UserResp struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserResp) Reset()         { *m = UserResp{} }
func (m *UserResp) String() string { return proto.CompactTextString(m) }
func (*UserResp) ProtoMessage()    {}
func (*UserResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_814acf6c55e120a3, []int{6}
}
func (m *UserResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserResp.Unmarshal(m, b)
}
func (m *UserResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserResp.Marshal(b, m, deterministic)
}
func (dst *UserResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserResp.Merge(dst, src)
}
func (m *UserResp) XXX_Size() int {
	return xxx_messageInfo_UserResp.Size(m)
}
func (m *UserResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UserResp.DiscardUnknown(m)
}

var xxx_messageInfo_UserResp proto.InternalMessageInfo

func (m *UserResp) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type User struct {
	Username             string   `protobuf:"bytes,1,opt,name=Username,proto3" json:"Username,omitempty"`
	FullName             string   `protobuf:"bytes,2,opt,name=FullName,proto3" json:"FullName,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=Description,proto3" json:"Description,omitempty"`
	FollowerCount        int64    `protobuf:"varint,4,opt,name=FollowerCount,proto3" json:"FollowerCount,omitempty"`
	ProfilePicUrl        string   `protobuf:"bytes,5,opt,name=ProfilePicUrl,proto3" json:"ProfilePicUrl,omitempty"`
	FeaturedPicUrl       string   `protobuf:"bytes,6,opt,name=FeaturedPicUrl,proto3" json:"FeaturedPicUrl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_814acf6c55e120a3, []int{7}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

func (m *User) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *User) GetFollowerCount() int64 {
	if m != nil {
		return m.FollowerCount
	}
	return 0
}

func (m *User) GetProfilePicUrl() string {
	if m != nil {
		return m.ProfilePicUrl
	}
	return ""
}

func (m *User) GetFeaturedPicUrl() string {
	if m != nil {
		return m.FeaturedPicUrl
	}
	return ""
}

func init() {
	proto.RegisterType((*LoginReq)(nil), "api.LoginReq")
	proto.RegisterType((*LoginResp)(nil), "api.LoginResp")
	proto.RegisterType((*JobReq)(nil), "api.JobReq")
	proto.RegisterType((*JobResp)(nil), "api.JobResp")
	proto.RegisterType((*Users)(nil), "api.Users")
	proto.RegisterType((*UserReq)(nil), "api.UserReq")
	proto.RegisterType((*UserResp)(nil), "api.UserResp")
	proto.RegisterType((*User)(nil), "api.User")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_api_814acf6c55e120a3) }

var fileDescriptor_api_814acf6c55e120a3 = []byte{
	// 360 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0xcf, 0x4e, 0xc2, 0x40,
	0x10, 0xc6, 0x2d, 0xa5, 0x40, 0x87, 0x3f, 0x87, 0x8d, 0x87, 0xa6, 0x89, 0x11, 0x37, 0x42, 0xea,
	0x85, 0x03, 0x5c, 0xbc, 0x1a, 0x0d, 0x07, 0x62, 0x0c, 0xa9, 0xe1, 0x01, 0x0a, 0xac, 0xb0, 0xb1,
	0x76, 0x97, 0xdd, 0x56, 0x5f, 0xd4, 0x07, 0x32, 0x3b, 0x5b, 0xa0, 0xe5, 0xe0, 0xf1, 0xf7, 0x7d,
	0xdf, 0x4c, 0x76, 0x66, 0x07, 0xfc, 0x44, 0xf2, 0x89, 0x54, 0x22, 0x17, 0xc4, 0x4d, 0x24, 0xa7,
	0x63, 0xe8, 0xbc, 0x8a, 0x1d, 0xcf, 0x62, 0x76, 0x20, 0x21, 0x74, 0x0a, 0xcd, 0x54, 0x96, 0x7c,
	0xb1, 0xc0, 0x19, 0x3a, 0x91, 0x1f, 0x9f, 0x98, 0xde, 0x81, 0x5f, 0xe6, 0xb4, 0x24, 0xd7, 0xe0,
	0xe5, 0xe2, 0x93, 0x65, 0x65, 0xca, 0x02, 0xa5, 0xd0, 0x5a, 0x88, 0xb5, 0x69, 0x14, 0x40, 0x7b,
	0x9f, 0xe8, 0x7d, 0x9e, 0xec, 0xca, 0xc4, 0x11, 0xe9, 0x0c, 0xda, 0x98, 0xd1, 0x92, 0x0c, 0xa0,
	0xc1, 0xb7, 0xe8, 0xbb, 0x71, 0x83, 0x6f, 0xab, 0x45, 0x8d, 0x7a, 0x51, 0x04, 0xde, 0x4a, 0x33,
	0xa5, 0xc9, 0x2d, 0x78, 0xe6, 0x41, 0x3a, 0x70, 0x86, 0x6e, 0xd4, 0x9d, 0xfa, 0x13, 0x33, 0x8c,
	0xb1, 0x62, 0xab, 0xd3, 0x11, 0xb4, 0x11, 0xed, 0x30, 0xab, 0x8b, 0x61, 0x8e, 0x4c, 0x1f, 0xac,
	0x87, 0xcf, 0xb8, 0x81, 0xa6, 0xa9, 0xc5, 0x4c, 0xad, 0x25, 0xca, 0xf4, 0xd7, 0x81, 0xa6, 0xc1,
	0xff, 0xfa, 0x19, 0x6f, 0x5e, 0xa4, 0xe9, 0x9b, 0xf1, 0xec, 0xdb, 0x4f, 0x4c, 0x86, 0xd0, 0x7d,
	0x61, 0x7a, 0xa3, 0xb8, 0xcc, 0xb9, 0xc8, 0x02, 0x17, 0xed, 0xaa, 0x44, 0xee, 0xa1, 0x3f, 0x17,
	0x69, 0x2a, 0x7e, 0x98, 0x7a, 0x16, 0x45, 0x96, 0x07, 0x4d, 0xdc, 0x49, 0x5d, 0x34, 0xa9, 0xa5,
	0x12, 0x1f, 0x3c, 0x65, 0x4b, 0xbe, 0x59, 0xa9, 0x34, 0xf0, 0xb0, 0x53, 0x5d, 0x24, 0x63, 0x18,
	0xcc, 0x59, 0x92, 0x17, 0x8a, 0x6d, 0xcb, 0x58, 0x0b, 0x63, 0x17, 0xea, 0x74, 0x09, 0xee, 0x93,
	0xe4, 0x84, 0x82, 0xbb, 0x10, 0x6b, 0xd2, 0xc5, 0xa9, 0xed, 0xe7, 0x85, 0xbd, 0x33, 0x68, 0x49,
	0xaf, 0xc8, 0xa8, 0x5c, 0x40, 0xef, 0xbc, 0x1a, 0x76, 0x08, 0xfb, 0x15, 0x32, 0xb1, 0xe9, 0x23,
	0xf4, 0xf0, 0x40, 0xde, 0x99, 0xfa, 0xe6, 0x1b, 0x46, 0x22, 0xf0, 0x90, 0x89, 0x4d, 0x1e, 0x8f,
	0x2c, 0x1c, 0x54, 0xd1, 0x54, 0xae, 0x5b, 0x78, 0x8e, 0xb3, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff,
	0xa4, 0xd1, 0x15, 0x99, 0x9b, 0x02, 0x00, 0x00,
}
