apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: default
  name: htmltoimagedepl
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: htmltoimage
    spec:
      containers:
      - name: htmltoimage
        command: [
      		"./htmlToimage",
      		"--server_address=0.0.0.0:8080",
      		"--broker_address=0.0.0.0:10001",
      		"--selector=static",
      	]
        image: livelance/htmltoimage:v0.0.1
        env:
          - name: WEB_LOCAL
            value: "http://192.168.99.100:30001"
        ports:
        - containerPort: 8080
          name: facedetect-port