apiVersion: v1
kind: Service
metadata:
  name: facedetect
  namespace: default
  labels:
    app: facedetect
spec:
  type: NodePort
  ports:
  - port: 4000
    nodePort: 30004
    protocol: TCP
  selector:
    app: facedetect